version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgresvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: codestryke
    ports:
      - "5435:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.0.8.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ${PWD}/backend/hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:codestryke@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: codestryke
